-- USE mysql;
-- CREATE USER 'username'@'localhost' IDENTIFIED BY 'oz-password'-- username이라는 Host 만들고 권한 부여
-- SELECT * FROM user; 
-- SHOW GRANTS FOR 'username'@'localhost'; -- username이라는 호스트의 권한을 확인
-- SHOW GRANTS;
-- DROP USER 'username'@'localhost'; -- username 호스트를 삭제